#!/usr/bin/python

modelDict = {"longblob": "models.BinaryField()",
	"bool": "models.BooleanField()",
	"bool": "models.NullBooleanField()",
	"date": "models.DateField()",
	"time": "models.TimeField()",
	"datetime": "models.DateTimeField()",
	"bigint": "models.DurationField()",
	"integerAUTO_INCREMENT": "models.AutoField()",
	"bigint": "models.BigIntegerField()",
	"numeric(X,Y)": "models.DecimalField(decimal_places=X,max_digits=Y)",
	"double": "models.FloatField()",
	"integer": "models.IntegerField()",
	"unsigned": "models.PositiveIntegerField()",
	"smallint unsigned": "models.PositiveSmallIntegerField()",
	"smallint": "options.SmallIntegerField()",
	"varchar(150)": "models.CharField(max_length=150))",
	"longtext": "models.TextField()",
	"varchar(N)": "models.CommaSeparatedIntegerField(max_length=50)",
	"varchar(254)": "models.EmailField()",
	"varchar(100)": "models.FileField()",
	"varchar(100)": "models.FilePathField()",
	"varchar(100)": "models.ImageField()",
	"char(39)": "models.GenericIPAddressField()",
	"varchar(50)": "models.SlugField()",
	"varchar(200)": "models.URLField()",
	"char(32)": "models.UUIDField()",
	"text": "models.CharField(max_length=50)",
	"int": "models.IntegerField()",
	"varchar(X)": "models.CharField(max_length=X)"}
	
djangoTables = ['auth_group',
	'auth_group_permissions',
	'auth_permission',
	'auth_user',
	'auth_user_groups',
	'auth_user_user_permissions',
	'django_admin_log',
	'django_content_type',
	'django_migrations',
	'django_session'
]
